// This file is auto-generated by @hey-api/openapi-ts

export type AddressGalleryResult = {
    id: number;
    line1?: string | null;
    line2?: string | null;
    line3?: string | null;
    line4?: string | null;
    country?: string | null;
    region?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    provider_id: string;
};

export type CourseWithOptions = {
    id: string;
    academicYear: number;
    courseTitle: string;
    summary: string;
    provider_id: string;
    options?: Array<OptionsGalleryResult> | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type OptionsGalleryResult = {
    id: string;
    course_id: string;
    location?: string | null;
    duration: string;
    googleMapsUrl?: string | null;
    startDate?: string | null;
    Qualification?: string | null;
};

export type PaginatedCourseResponse = {
    total: number;
    page: number;
    per_page: number;
    data: Array<CourseWithOptions>;
};

export type PaginatedProviderResponse = {
    total: number;
    page: number;
    per_page: number;
    data: Array<ProviderWithAddress>;
};

export type ProviderWithAddress = {
    id: number;
    provider_ID: string;
    logoUrl: string;
    institution_code?: string | null;
    name: string;
    competition_level: string | null;
    course_count: number;
    address?: AddressGalleryResult | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type GetProvidersApiProvidersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of providers to return
         */
        limit?: number;
        /**
         * Include Address Information in Response
         */
        addresses?: boolean;
    };
    url: '/api/providers/';
};

export type GetProvidersApiProvidersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProvidersApiProvidersGetError = GetProvidersApiProvidersGetErrors[keyof GetProvidersApiProvidersGetErrors];

export type GetProvidersApiProvidersGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedProviderResponse;
};

export type GetProvidersApiProvidersGetResponse = GetProvidersApiProvidersGetResponses[keyof GetProvidersApiProvidersGetResponses];

export type SearchProvidersApiProvidersSearchGetData = {
    body?: never;
    path?: never;
    query: {
        name: string;
    };
    url: '/api/providers/search';
};

export type SearchProvidersApiProvidersSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchProvidersApiProvidersSearchGetError = SearchProvidersApiProvidersSearchGetErrors[keyof SearchProvidersApiProvidersSearchGetErrors];

export type SearchProvidersApiProvidersSearchGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ProviderWithAddress>;
};

export type SearchProvidersApiProvidersSearchGetResponse = SearchProvidersApiProvidersSearchGetResponses[keyof SearchProvidersApiProvidersSearchGetResponses];

export type SearchCoursesApiCoursesGetData = {
    body?: never;
    path?: never;
    query: {
        provider_id: string;
        /**
         * Include options in response
         */
        options?: boolean;
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        limit?: number;
    };
    url: '/api/courses/';
};

export type SearchCoursesApiCoursesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchCoursesApiCoursesGetError = SearchCoursesApiCoursesGetErrors[keyof SearchCoursesApiCoursesGetErrors];

export type SearchCoursesApiCoursesGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedCourseResponse;
};

export type SearchCoursesApiCoursesGetResponse = SearchCoursesApiCoursesGetResponses[keyof SearchCoursesApiCoursesGetResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};